[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[all]>=0.129.0",
    "passlib[bcrypt]>=1.7.4",
    "pytest>=8.4.2",
    "pymysql>=1.1.2",
    "python-dotenv>=1.2.1",
    "python-jose>=3.5.0",
    "sqlmodel>=0.0.34",
    "uvicorn[standard]>=0.41.0",
]
